name: Publish Release

on:
  workflow_dispatch:

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Variable Gathering
        id: gathervars
        run: |
          # get a current BUILD_DATE

          echo "::set-output name=BUILD_DATE::$(date +%Y%m%d-%H%M%S)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            BUILD_DATE=${{ steps.gathervars.outputs.BUILD_DATE }}
            VERSION=${{ steps.gathervars.outputs.BUILD_DATE }}
          context: ./docker/production
          tags: ghcr.io/${{ github.repository }}:${{ steps.gathervars.outputs.BUILD_DATE }}
          platforms: ${{ env.PLATFORMS }}
          push: true
